[package]
name = "rogueliketutorial"
version = "0.1.0"
authors = ["Jarlish"]
edition = "2018"

[dependencies]
rltk = { git = "https://github.com/amethyst/bracket-lib" }
specs = "0.17.0"
specs-derive = "0.4.1"
